### ISSUE TITLE
Refactor `App.css` to resolve potential Leaflet map sizing issues

### ISSUE THREAD

**Issue by kaashmonee** [Lifespark-Technologies/Infomed#22]
As commented by @bl-nero in PR #15: https://github.com/Lifespark-Technologies/Infomed/pull/15#discussion_r419996570, we should consider moving the leaflet container height declaration to index.css. This could resolve bugs where the map overflows the entire page.

**Comment by bl-nero** [comment]
@kaashmonee Make sure to coordinate with Ameen, he's working on moving the header into a hamburger menu.
