### ISSUE TITLE
Enable hospital admins to edit list of resources

### ISSUE THREAD

**Issue by bl-nero** [Lifespark-Technologies/Infomed#49]
This is more or less how it should look like: 

![image](https://user-images.githubusercontent.com/9391503/82381871-3adc2a80-9a2b-11ea-8eef-c0b14862bb3e.png)

(But we should make it consistent with existing design.)

**Comment by naijauser** [comment]
I have a question, what are the listed items? Images? Checkboxes?

**Comment by bl-nero** [comment]
Ah, these items. I _think_ these are text boxes, but you may want to confirm that with Amey (I have the screenshot from him). Also note that it turned out that for at least some of these will have two values (total amount and available amount, like in total beds and available beds). See the [product requirements document](https://docs.google.com/document/d/1t_qJyg5nIntLCNdRlBsm_vtGw7zMwJUEZ1Kem7tQKWU/edit), section "Flow (currently considered)".

**Comment by bl-nero** [comment]
@naijauser Small correction: there's always going to be a single text box for the available number of resources. The total number will be fixed upon the registration.
